<div class="user_profile">
    <div class="img_circle user_profile_img_block">
        <img src="../../img/avatar.png" alt="avatar">
    </div>
    <div class="user_profile_info_block">
        <div class="user_profile_row">
            <p>name:</p>
            <h5 class="user_profile_name">Alex123</h5>
            <span id='user_profile_name' class="material-symbols-outlined edit_icon">edit</span>
        </div>
        <div class="user_profile_row">
            <p>surname</p>
            <h5 class="user_profile_surname">Smith</h5>
            <span id='user_profile_surname' class="material-symbols-outlined edit_icon">edit</span>
        </div>
        <div class="user_profile_row">
            <p>country</p>
            <h5 class="user_profile_country">USA</h5>
            <span id='user_profile_country' class="material-symbols-outlined edit_icon">edit</span>
        </div>
        <div class="user_profile_row">
            <p>slogan</p>
            <h5 class="user_profile_slogan">All by myself</h5>
            <span id='user_profile_slogan' class="material-symbols-outlined edit_icon">edit</span>
        </div>
        <div class="user_profile_row">
            <p>likes:</p>
            <h5 class="user_profile_likes">1</h5>
        </div>
        <div class="user_profile_row">
            <p>comments:</p>
            <h5 class="user_profile_comments">1</h5>
        </div>
    </div>
</div>