<div class="auth-block">
    <div class="login_block">
        <div class="img_circle">
            <img src="../../img/avatar.png" alt="avatar">
        </div>
        <div class="login_name_block">
            <p><?= htmlspecialchars($login) ?></p>
            <div class="login_button_block">
                <a href='logout' class="button button_profile">Profile</a>
                <a href='logout' class="button">Exit</a>
            </div>
        </div>
    </div>
</div>