<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css"/>
    <link rel="stylesheet" type="text/css" href="<?= $css_path ?>">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Borel&family=Montserrat:wght@500&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="<?= $icon_path ?>" type="image/x-icon">
    <title>Travelers</title>
</head>
<body>
<?= $container ?>
    
    <?php 
        foreach($scripts as $key => $value){
            echo "<script src=" . $scripts[$key] . "></script>";
        }
    ?>
</body>
</html>